language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
install: composer install
script: ./bin/phpunit -c tests/phpunit/phpunit.xml

matrix:
  include:
  - php: 7.2
    install: composer require --dev phpstan/phpstan
    script: composer static-analysis

after_success:
    - bash <(curl -s https://codecov.io/bash)
